// Generated by CoffeeScript 1.10.0
var Foswig, chain, dictionary, i;

Foswig = require('./dist/foswig.js');

chain = new Foswig(3);

dictionary = require('./dictionary-gr');

console.log("Compiling Greek Dictionary. This process may take up to 60 seconds. Please wait...");

console.time('dict');

chain.addWordsToChain(dictionary);

console.timeEnd('dict');

i = 0;

while (i < 10) {
  console.log(chain.generateWord(6, 12, false));
  i++;
}
