// Generated by CoffeeScript 1.10.0
var end, fs, output, read, readline, start;

fs = require('fs');

readline = require('readline');

output = "dictionary-gr.js";

start = "module.exports = [";

end = "''];";

fs.writeFile(output, start, function(err) {
  return err;
});

read = readline.createInterface({
  input: fs.createReadStream("el_GR.dic"),
  output: process.stdout,
  terminal: false
});

read.on('line', function(line) {
  line = line.replace(/\/.+/, "");
  console.log("'" + line + "',");
  return fs.appendFile(output, "'" + line + "',", function(err) {
    return err;
  });
});

read.on('close', function() {
  console.log('Finished parsing...');
  return fs.appendFile(output, end, function(err) {
    return err;
  });
});
